local ui_utils = {}

function ui_utils.cursor(x, y)
  screen.level(9)
  screen.move(x-3,y+3)
  screen.line(x,y)
  screen.line_rel(3,3)
  screen.stroke()
end

function ui_utils.tape(x,y) -- 75,10
  screen.level(selected == 2 and 2 or 1)
  screen.rect(79,46,36,10)
  screen.fill()
  screen.level(0)
  screen.move(88,54)
  screen.text("TAPE")
  screen.stroke()

  screen.level(8)
  screen.rect(x,y,45,25)
  screen.fill()

  screen.level(0)
  screen.rect(x, y, 1, 1)
  screen.rect(x + 44, y, 1, 1)
  screen.rect(x, y + 24, 1, 1)
  screen.rect(x + 44, y + 24, 1, 1)
  screen.fill()

  screen.level(2)
  screen.rect(x + 2, y + 3, 41, 16)
  screen.fill()

  screen.level(8)
  screen.rect(x + 2, y + 3, 1, 1)
  screen.rect(x + 42, y + 3, 1, 1)
  screen.rect(x + 2, y + 18, 1, 1)
  screen.rect(x + 42, y+18, 1, 1)
  screen.fill()

  screen.level(4)
  screen.rect(x + 8, y + 22,29,3)
  screen.rect(x + 2,y+ 22,1,1)
  screen.rect(x + 42 ,y + 22,1,1)
  screen.fill()

  screen.level(6)
  screen.circle(x + 12 , y+ 11,4)
  screen.circle(x + 33 ,y + 11,4)
  screen.fill()
  screen.level(2)
  screen.circle(x + 12,y + 11,1)
  screen.circle(x + 33,y+11,1)
  screen.fill()
  screen.level(3)
  screen.rect(x + 17,y + 9,11,4)
  screen.fill()
end

function ui_utils.op_icon(x, y, connected)
  local c1 = 0
  local c2 = 0
  screen.level(connected and 6 or 2 )
  screen.rect(x, y, 63, 22)
  screen.fill()
  screen.level(0)
  screen.rect(x,y+21,1,1)
  screen.rect(x+62,y,1,1)
  screen.rect(x,y,1,1)
  screen.rect(x+62,y+21,1,1)
  screen.fill()

  screen.level(1)
  screen.rect(x + 17 ,y + 2, 12, 5)
  screen.fill()
  screen.stroke()
  --- todo loop
  screen.circle(x + 12, y + 5, 2)
  screen.fill()
  for i=1,4 do
    screen.circle((x + 29) + (i *6), y + 5, 2)
    screen.fill()
  end
  screen.fill()
  screen.pixel(x + 2, y + 2)
  screen.fill()
  screen.pixel(x + 4, y + 2)
  screen.fill()
  screen.pixel(x + 6, y + 2)
  screen.fill()
  screen.pixel(x + 2, y + 4)
  screen.fill()
  screen.pixel(x + 4, y + 4)
  screen.fill()
  screen.pixel(x + 6, y + 4)
  screen.fill()
  screen.pixel(x + 2, y + 6)
  screen.fill()
  screen.pixel(x + 4, y + 6)
  screen.fill()
  screen.pixel(x + 6, y + 6)
  screen.fill()

  for i=1,15 do
    screen.rect(x + (3 + c1), y + 10, 2, 2)
    screen.stroke()
    c1 = c1 + 4
  end
  for i=1,13 do
    screen.rect(x + (11 + c2), y + 14, 2, 6)
    screen.stroke()
    c2 = c2 + 4
  end

  screen.rect(x + 3, y + 14, 2, 2)
  screen.stroke()
  screen.rect(x + 3, y + 18, 2, 2)
  screen.stroke()
  screen.rect(x + 7, y + 14, 2, 2)
  screen.stroke()
  screen.rect(x + 7, y + 18, 2, 2)
  screen.stroke()

  if connected then
    screen.level(3)
    screen.rect(x+63,y+10,4,3)
    screen.fill()
    screen.move(x+63,y+12)
    screen.line(x+120,y+12)
    screen.stroke()
  end
end

function ui_utils.edit_icon(x,y)
   --- text
  screen.level(selected == 1 and 2 or 1)
  screen.rect(x+12,y+12,36,10)
  screen.fill()
  screen.level(0)
  screen.move(x+15,y+20)
  screen.text("PRESETS")
  screen.stroke()
  -- pencil
  screen.level(1)
  screen.line_width(1.5)
  screen.move(x+2,y)
  screen.line_rel(10,10)
  screen.move(x,y+1)
  screen.line_rel(10,10)
  screen.stroke()
  --
  screen.level(6)
  screen.line_width(1)
  screen.move(x,y-1)
  screen.line_rel(3,1)
  screen.stroke()
  screen.move(x,y)
  screen.line_rel(0,3)
  screen.stroke()
  screen.move(x+1,y+1)
  screen.line_rel(11,11)
  screen.move(x + 3,y)
  screen.line_rel(9,9)
  screen.move(x,y+3)
  screen.line_rel(10,10)
  screen.stroke()
  screen.move(x,y)
  screen.line_rel(1,1)
  screen.stroke()
  screen.move(x+13,y+9)
  screen.line_rel(0, 4)
  screen.line_rel(-3, -2)
  screen.stroke()
  screen.move(x+9,y+13)
  screen.line_rel(3,0)
  screen.line_rel(0,-3)
  screen.stroke()
end

function ui_utils.sync_icon(x,y)
  screen.level(6)
  screen.circle(x,y+5,8)
  screen.fill()

  screen.level(0)
  screen.circle(x,y+5,5.5)
  screen.fill()
  screen.line_width(7)
  screen.move(x-10,y-5)
  screen.line_rel(20,20)
  screen.stroke()

  screen.line_width(1)
  screen.level(6)
  screen.move(x-12,y+3)
  screen.line_rel(6,-5)
  screen.line_rel(5,5)
  screen.fill()

  screen.level(6)
  screen.move(x+12,y+7)
  screen.line_rel(-4,5)
  screen.line_rel(-5,-5)
  screen.fill()

  screen.level(selected == 2 and 2 or 1)
  screen.rect(x+6,y+12,33,10)
  screen.fill()
  screen.level(0)
  screen.move(x+9,y+20)
  screen.text("BACKUP")
end

function ui_utils.album_icon(x, y, lp_pos) 
  screen.level(selected == 1 and 2 or 1)
  screen.rect(x - 18, y + 26,36,10)
  screen.fill()
  screen.level(0)
  screen.move(x - 13, y + 34)
  screen.text("ALBUM")
  screen.stroke()

  screen.level(2)
  screen.circle(x,y,15)
  screen.stroke()
  screen.level(4)
  screen.circle(x,y,14)
  screen.stroke()
  screen.level(2)
  screen.circle(x,y,13)
  screen.stroke()
  screen.level(4)
  screen.circle(x,y,12)
  screen.stroke()
  screen.level(2)
  screen.circle(30,20,11)
  screen.stroke()
  screen.level(4)
  screen.circle(x,y,10)
  screen.stroke()
  screen.level(2)
  screen.circle(x,y,9)
  screen.stroke()
  screen.level(4)
  screen.circle(x,y,8)
  screen.stroke()
  screen.level(2)
  screen.circle(x,y,7)
  screen.stroke()
  screen.level(4)
  screen.circle(x,y,6)
  screen.stroke()
  screen.level(2)
  screen.circle(x,y,5)
  screen.stroke()
  screen.level(4)
  screen.circle(x,y,4)
  screen.stroke()
  screen.level(2)
  screen.circle(x,y,3)
  screen.stroke()
  screen.level(4)
  screen.circle(x,y,2)
  screen.stroke()
  screen.level(2)
  screen.circle(x,y,1)
  screen.stroke()
  screen.level(2)
  --- funky LP design
  screen.rect(x - 18, lp_pos,36,33)
  screen.fill()
  screen.level(1)
  screen.move(x - 16,lp_pos + 7)
  screen.text("/////.")
  screen.stroke()
  screen.level(1)
  screen.move(x - 17,lp_pos + 15)
  screen.text("...............")
  screen.move(x - 13,lp_pos + 16)
  screen.text("...............")
  screen.move(x - 17,lp_pos + 13)
  screen.text(".............")
  screen.move(x - 13,lp_pos + 18)
  screen.text("...............")
  screen.move(x - 17,lp_pos + 14)
  screen.text(".............")
  screen.move(x - 13,lp_pos + 17)
  screen.text("............")
  screen.stroke()

end

return ui_utils